config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root 'welcome#index'
  resources :events do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_rich_text :content
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_rich_text :body
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################

  before_save { self.email = email.downcase }

  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable
  has_many :events
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CurrentUserConcern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @event = Event.find(params[:event_id])
    @event.comments.create(comment_params.merge(user: current_user))
    redirect_to event_path(@event)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    GuestUser.new(
      username: 'Guest User',
      first_name: 'Guest',
      last_name: 'User',
      email: 'guest@example.com'
    )
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create destroy]
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    @event.user = current_user
    if @event.save
      redirect_to events_path
    else
      render 'edit'
    end
  end

  def edit
    
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'new'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/events/_comment_form.haml
= simple_form_for @comment, url: event_comments_path(@event) do |f|
  = f.rich_text_area :content
  %br
  = f.button :submit, class: "btn btn-md btn-primary"

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  = f.input :title
  = f.rich_text_area :body
  %br
  = f.button :submit, class: "btn btn-md btn-primary"

app/views/events/edit.html.haml
%h2 Update Your Event
= render 'form'
= link_to 'Cancel', event_path

app/views/events/index.html.haml
- @events.each do |event|
  %h2= link_to event.title, event
  %p= time_ago_in_words(event.created_at)
  %p= event.body

app/views/events/new.html.haml
%h2 New Event
= render 'form'

app/views/events/show.html.haml
%div{class: "col-lg-5"}
  %h1= @event.title
  %p= @event.body
  %br/
  - @event.comments.each do |comment|
    %span #{comment.user.username} says:
    %hr/
    %p #{comment.content}
    %p #{comment.created_at}
  %br/
  %h2 Comment
  = render 'comment_form'

  = link_to 'Upcoming Events', events_path
  = link_to 'Update Event', edit_event_path(@event)
  = link_to 'Cancel Event', event_path(@event), method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-primary.fixed-top
  .container
    = link_to "Navbar", root_path, class: "navbar-brand"
    %button.navbar-toggler{ type: "button", "data-toggle" => :collapse, "data-target" => "#navbarSupportedContent", "aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}
      %span.navbar-toggler-icon

    .collapse.navbar-collapse#navbarSupportedContent
      %ul.nav.navbar-nav.mr-auto.nav-pills.nav-fill
        %li.nav-item.active
          = link_to "Home", root_path, class: "nav-link"

        %li.nav-item
          = link_to "Nav Link Two", "#", class: "nav-link"

        - if user_signed_in?
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle#navbarDropdown{href: "#", role: "button", "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" }
              Dropdown
            .dropdown-menu{ "aria-labelledby" => "navbarDropdown" }
              %a.dropdown-item{href: "#" }Account
              = link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item"
              %a.dropdown-item{href: "#" }Friendly Gatherers
              .dropdown-divider
              = link_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item"
        - else
          %li.nav-item
          = link_to "Nav Link Two", "#", class: "nav-link"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Good2Gather
    = stylesheet_link_tag "application", :media => "all", 'data-turbolinks-track': 'reload'
    = javascript_pack_tag "application", 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    %p.notice
      = notice
    %p.alert
      = alert
    = render 'layouts/header'
    .container
      = yield

app/views/welcome/index.html.haml
%h1 Voila This Works!

%strong{class: "code"} Hello HAML!